import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  fts: [
    'filament-translation-suite/getting-started',
    'filament-translation-suite/installation',
    'filament-translation-suite/configuration',
    'filament-translation-suite/authorization',
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'filament-translation-suite/features' }],
    },
    'filament-translation-suite/pricing',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'filament-translation-suite/reference/events',
        'filament-translation-suite/reference/exceptions',
      ],
    },
  ],
  fwl: [
    'filament-white-label/getting-started',
    'filament-white-label/installation',
    'filament-white-label/configuration',
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'filament-white-label/features' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'filament-white-label/reference/resolution-flow',
        'filament-white-label/reference/cache-and-security',
        'filament-white-label/reference/events',
      ],
    },
  ],
};

export default sidebars;
